[project]
name = "indecimal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.27",
    "pypdf2>=3.0.1",
    "streamlit>=1.50.0",
]
